### ISSUE TITLE
CORS issue exists with 2.4 

### ISSUE THREAD

**Issue by Kriyainc** [ajbrown/angular-loggly-logger#66]
Angular projects with custom headers still experience CORS issue. Kicks off Options requests to which the server responds with 405

**Comment by flastowizka** [comment]
i had this problem too:

**Comment by krupak** [comment]
I am having the same problem. It works in my one project but not working in the other. Need help to fix this asap as I have release it in production. The request which goes to loggly returns 405 method not allowed error.

**Comment by Kriyainc** [comment]
I downgraded to I think 1.3 to "fix" the issue

**Comment by ajbrown** [comment]
Hi Everyone,

Sorry for the delay on this, things have been very busy for me.  I will work on getting this resolved and merged in this week.  If anyone is willing to submit a PR for the fix, that would speed things up.

**Comment by ajbrown** [comment]
This should be fixed with the latest release.

**Comment by makmonty** [comment]
Still happening in v0.3.1. Anyway, I'm using Npm to install this library and the published version is still 0.2.4

**Comment by tabuna** [comment]
I'm on version 0.3.1 (on 6 Mar) and experience similar difficulties

> Failed to load https://logs-01.loggly.com/inputs/*******: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 400
